/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package ClientGUIv2;

import ClientGUI.ForumPanel;
import ClientSrc.ConnectionHandler;
import java.awt.CardLayout;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sivan
 */
public class MainFrame extends javax.swing.JFrame {
    
    private ConnectionHandler handler;
    
    private JDialog fDialog;
    private ForumPanel fPanel;
    private boolean confirmed=false;
    private DefaultTableModel allForumsModel;
    private DefaultTableModel allSubForumsModel;
    private DefaultTableModel adminsModel;
    private DefaultTableModel allTopicsModel;
    private DefaultTableModel moderatorsModel;
    private String chosenForum;
    private String userName;
    private int superAdminRegister = 0; //declares on what page he was registered as admin
    private String chosenSubForum;
    private String serverResponse;
    public static final int FORUMFRAME = 1;
    public static final int SUBFORUMFRAME = 2;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        handler = new ConnectionHandler();
        
        registerMainPanel.setVisible(false);
        createSubMainPanel.setVisible(false);
        permissionMainPanel.setVisible(false);
        createForumMainPanel.setVisible(false);
        
        initTableListener();
        buttonAppearance("guest");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        allForumsPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        forumLoginButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        forumsTable = new javax.swing.JTable();
        saLabel = new javax.swing.JLabel();
        forumCreateButton = new javax.swing.JButton();
        forumDeleteButton = new javax.swing.JButton();
        allSubForumPanel = new javax.swing.JPanel();
        subRegistrationButton = new javax.swing.JButton();
        subLogoutButton = new javax.swing.JButton();
        subDeleteButton = new javax.swing.JButton();
        subCreateButton = new javax.swing.JButton();
        subAddAdminButton = new javax.swing.JButton();
        subRemoveAdminButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminsTable = new javax.swing.JTable();
        subWelcomeToLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subForumTable = new javax.swing.JTable();
        subLoginButton = new javax.swing.JButton();
        subBackButton = new javax.swing.JButton();
        allTopicsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        topicsTable = new javax.swing.JTable();
        topicsRegistrationButton = new javax.swing.JButton();
        topicsLoginButton = new javax.swing.JButton();
        topicsLogoutButton = new javax.swing.JButton();
        topicsBackButton = new javax.swing.JButton();
        topicsDeleteButton = new javax.swing.JButton();
        topicsAddButton = new javax.swing.JButton();
        topicsAddModeratorButton = new javax.swing.JButton();
        topicsRemoveModeratorButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        moderatorsTable = new javax.swing.JTable();
        topicsWelcomeToLabel = new javax.swing.JLabel();
        registerMainPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        registerToForumLabel = new javax.swing.JLabel();
        registerUserNameLabel = new javax.swing.JLabel();
        registerPasswordLabel = new javax.swing.JLabel();
        registerRemainderQuesLabel = new javax.swing.JLabel();
        registerEmailLabel = new javax.swing.JLabel();
        registerRemainderAnsLabel = new javax.swing.JLabel();
        registerEmailText = new javax.swing.JTextField();
        registerRemainderQuesText = new javax.swing.JTextField();
        registerRemainderAnsText = new javax.swing.JTextField();
        registerSubmitButton = new javax.swing.JButton();
        registerUserNameText = new javax.swing.JTextField();
        registerCancelButton = new javax.swing.JButton();
        registerPasswordText = new javax.swing.JTextField();
        createSubMainPanel = new javax.swing.JPanel();
        createSubForumPanel = new javax.swing.JPanel();
        openSubSubjectLabel = new javax.swing.JLabel();
        openSubModeratorLabel = new javax.swing.JLabel();
        openSubSubjectText = new javax.swing.JTextField();
        openSubNameText = new javax.swing.JTextField();
        openSubForumLabel = new javax.swing.JLabel();
        openSubNameLabel = new javax.swing.JLabel();
        openSubModeratortext = new javax.swing.JTextField();
        openSubSubmitButton = new javax.swing.JButton();
        openSubCancelButton = new javax.swing.JButton();
        permissionMainPanel = new javax.swing.JPanel();
        permissionPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        titel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        permissionSubmitButton = new javax.swing.JButton();
        permissionPasswordField = new javax.swing.JPasswordField();
        createForumMainPanel = new javax.swing.JPanel();
        createForumPanel = new javax.swing.JPanel();
        forumSubmitButton = new javax.swing.JButton();
        forumPolicyText = new javax.swing.JTextField();
        forumCancelButton = new javax.swing.JButton();
        forumNameText = new javax.swing.JTextField();
        openSubForumLabel1 = new javax.swing.JLabel();
        forumPolicyLabel = new javax.swing.JLabel();
        forumNameLabel = new javax.swing.JLabel();
        forumSecurityLabel = new javax.swing.JLabel();
        forumSecurityText = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeLabel.setText("WELCOME !");

        forumLoginButton.setText("Login");
        forumLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumLoginButtonActionPerformed(evt);
            }
        });

        forumsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "All Forums"
            }
        ));
        jScrollPane1.setViewportView(forumsTable);

        saLabel.setText("For super administrator:");

        forumCreateButton.setText("Create Forum");
        forumCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumCreateButtonActionPerformed(evt);
            }
        });

        forumDeleteButton.setText("Delete Forum");
        forumDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allForumsPanelLayout = new javax.swing.GroupLayout(allForumsPanel);
        allForumsPanel.setLayout(allForumsPanelLayout);
        allForumsPanelLayout.setHorizontalGroup(
            allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allForumsPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(allForumsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forumCreateButton)
                            .addComponent(forumDeleteButton)))
                    .addGroup(allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(allForumsPanelLayout.createSequentialGroup()
                            .addComponent(saLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(forumLoginButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(allForumsPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(welcomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        allForumsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {forumCreateButton, forumDeleteButton});

        allForumsPanelLayout.setVerticalGroup(
            allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allForumsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel)
                .addGap(37, 37, 37)
                .addGroup(allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(allForumsPanelLayout.createSequentialGroup()
                        .addComponent(forumCreateButton)
                        .addGap(11, 11, 11)
                        .addGroup(allForumsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forumDeleteButton)
                            .addComponent(forumLoginButton)
                            .addComponent(saLabel)))
                    .addGroup(allForumsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addContainerGap())
        );

        mainPanel.add(allForumsPanel, "card2");

        subRegistrationButton.setText("Register");
        subRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRegistrationButtonActionPerformed(evt);
            }
        });

        subLogoutButton.setText("Logout");
        subLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLogoutButtonActionPerformed(evt);
            }
        });

        subDeleteButton.setText("Delete Sub Forum");
        subDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDeleteButtonActionPerformed(evt);
            }
        });

        subCreateButton.setText("Create Sub Forum");
        subCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCreateButtonActionPerformed(evt);
            }
        });

        subAddAdminButton.setText("Add Administrator");
        subAddAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAddAdminButtonActionPerformed(evt);
            }
        });

        subRemoveAdminButton.setText("Remove Administrator");
        subRemoveAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRemoveAdminButtonActionPerformed(evt);
            }
        });

        adminsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Supported By:"
            }
        ));
        jScrollPane2.setViewportView(adminsTable);

        subWelcomeToLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subWelcomeToLabel.setText("Welcome to ");

        subForumTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sub Forum List"
            }
        ));
        jScrollPane3.setViewportView(subForumTable);

        subLoginButton.setText("Login");
        subLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLoginButtonActionPerformed(evt);
            }
        });

        subBackButton.setText("Back");
        subBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allSubForumPanelLayout = new javax.swing.GroupLayout(allSubForumPanel);
        allSubForumPanel.setLayout(allSubForumPanelLayout);
        allSubForumPanelLayout.setHorizontalGroup(
            allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSubForumPanelLayout.createSequentialGroup()
                .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allSubForumPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(allSubForumPanelLayout.createSequentialGroup()
                                .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subRemoveAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subAddAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subDeleteButton))
                            .addGroup(allSubForumPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(allSubForumPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subLogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subRegistrationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subLoginButton)))
                .addGap(29, 29, 29))
            .addGroup(allSubForumPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(subWelcomeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        allSubForumPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {subLoginButton, subLogoutButton, subRegistrationButton});

        allSubForumPanelLayout.setVerticalGroup(
            allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSubForumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subLoginButton)
                    .addComponent(subRegistrationButton)
                    .addComponent(subLogoutButton)
                    .addComponent(subBackButton))
                .addGap(33, 33, 33)
                .addComponent(subWelcomeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allSubForumPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(allSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subDeleteButton)
                            .addComponent(subCreateButton)))
                    .addGroup(allSubForumPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subAddAdminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subRemoveAdminButton)))
                .addGap(58, 58, 58))
        );

        allSubForumPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {subLoginButton, subLogoutButton, subRegistrationButton});

        mainPanel.add(allSubForumPanel, "card4");

        topicsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Topics"
            }
        ));
        jScrollPane4.setViewportView(topicsTable);

        topicsRegistrationButton.setText("Register");
        topicsRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsRegistrationButtonActionPerformed(evt);
            }
        });

        topicsLoginButton.setText("Login");
        topicsLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsLoginButtonActionPerformed(evt);
            }
        });

        topicsLogoutButton.setText("Logout");
        topicsLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsLogoutButtonActionPerformed(evt);
            }
        });

        topicsBackButton.setText("Back");
        topicsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsBackButtonActionPerformed(evt);
            }
        });

        topicsDeleteButton.setText("Delete Topic");
        topicsDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsDeleteButtonActionPerformed(evt);
            }
        });

        topicsAddButton.setText("Add Topic");
        topicsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsAddButtonActionPerformed(evt);
            }
        });

        topicsAddModeratorButton.setText("Add Moderator");
        topicsAddModeratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsAddModeratorButtonActionPerformed(evt);
            }
        });

        topicsRemoveModeratorButton.setText("Remove Moderator");
        topicsRemoveModeratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsRemoveModeratorButtonActionPerformed(evt);
            }
        });

        moderatorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Supported By:"
            }
        ));
        jScrollPane5.setViewportView(moderatorsTable);

        topicsWelcomeToLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topicsWelcomeToLabel.setText("Welcome to ");

        javax.swing.GroupLayout allTopicsPanelLayout = new javax.swing.GroupLayout(allTopicsPanel);
        allTopicsPanel.setLayout(allTopicsPanelLayout);
        allTopicsPanelLayout.setHorizontalGroup(
            allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allTopicsPanelLayout.createSequentialGroup()
                .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allTopicsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topicsBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(topicsLogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topicsRegistrationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topicsLoginButton))
                    .addGroup(allTopicsPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(allTopicsPanelLayout.createSequentialGroup()
                                .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(topicsRemoveModeratorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(topicsAddModeratorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(topicsAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(topicsDeleteButton))
                            .addGroup(allTopicsPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addGroup(allTopicsPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(topicsWelcomeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        allTopicsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {topicsLoginButton, topicsLogoutButton, topicsRegistrationButton});

        allTopicsPanelLayout.setVerticalGroup(
            allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allTopicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topicsLoginButton)
                    .addComponent(topicsRegistrationButton)
                    .addComponent(topicsLogoutButton)
                    .addComponent(topicsBackButton))
                .addGap(35, 35, 35)
                .addComponent(topicsWelcomeToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allTopicsPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(allTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(topicsDeleteButton)
                            .addComponent(topicsAddButton)))
                    .addGroup(allTopicsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(topicsAddModeratorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topicsRemoveModeratorButton)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mainPanel.add(allTopicsPanel, "card5");

        registerMainPanel.setLayout(new java.awt.CardLayout());

        registerToForumLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerToForumLabel.setText("Register");

        registerUserNameLabel.setText("User name:");

        registerPasswordLabel.setText("Password:");

        registerRemainderQuesLabel.setText("Reminder question:");

        registerEmailLabel.setText("E-mail:");

        registerRemainderAnsLabel.setText("Remainder answer:");

        registerSubmitButton.setText("Submit");
        registerSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSubmitButtonActionPerformed(evt);
            }
        });

        registerCancelButton.setText("Cancel");
        registerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(registerToForumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(registerCancelButton))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerSubmitButton)
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registerRemainderAnsLabel)
                                .addComponent(registerRemainderQuesLabel)
                                .addComponent(registerEmailLabel)
                                .addComponent(registerPasswordLabel)
                                .addComponent(registerUserNameLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerEmailText)
                            .addComponent(registerUserNameText)
                            .addComponent(registerRemainderQuesText)
                            .addComponent(registerRemainderAnsText)
                            .addComponent(registerPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {registerEmailLabel, registerPasswordLabel, registerRemainderAnsLabel, registerRemainderQuesLabel, registerUserNameLabel});

        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(registerToForumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerRemainderQuesLabel)
                    .addComponent(registerRemainderQuesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerRemainderAnsLabel)
                    .addComponent(registerRemainderAnsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerSubmitButton)
                    .addComponent(registerCancelButton))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        registerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {registerPasswordLabel, registerRemainderAnsLabel, registerRemainderQuesLabel});

        registerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {registerEmailLabel, registerEmailText});

        registerMainPanel.add(registerPanel, "card2");

        createSubMainPanel.setLayout(new java.awt.CardLayout());

        openSubSubjectLabel.setText("Subject:");

        openSubModeratorLabel.setText("Moderator:");

        openSubForumLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openSubForumLabel.setText("Open new sub forum");
        openSubForumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        openSubNameLabel.setText("Sub Forum Name:");

        openSubSubmitButton.setText("Submit");
        openSubSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSubSubmitButtonActionPerformed(evt);
            }
        });

        openSubCancelButton.setText("Cancel");
        openSubCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSubCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createSubForumPanelLayout = new javax.swing.GroupLayout(createSubForumPanel);
        createSubForumPanel.setLayout(createSubForumPanelLayout);
        createSubForumPanelLayout.setHorizontalGroup(
            createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createSubForumPanelLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createSubForumPanelLayout.createSequentialGroup()
                        .addComponent(openSubForumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createSubForumPanelLayout.createSequentialGroup()
                        .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openSubSubjectLabel)
                            .addComponent(openSubNameLabel)
                            .addComponent(openSubModeratorLabel))
                        .addGap(30, 30, 30)
                        .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openSubModeratortext)
                            .addComponent(openSubNameText)
                            .addComponent(openSubSubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
            .addGroup(createSubForumPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(openSubSubmitButton)
                .addGap(59, 59, 59)
                .addComponent(openSubCancelButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        createSubForumPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {openSubModeratorLabel, openSubNameLabel, openSubSubjectLabel});

        createSubForumPanelLayout.setVerticalGroup(
            createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSubForumPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(openSubForumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openSubNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openSubNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openSubSubjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openSubSubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(openSubModeratortext)
                    .addComponent(openSubModeratorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(createSubForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openSubSubmitButton)
                    .addComponent(openSubCancelButton))
                .addGap(137, 137, 137))
        );

        createSubForumPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {openSubNameLabel, openSubNameText});

        createSubMainPanel.add(createSubForumPanel, "card2");

        permissionMainPanel.setLayout(new java.awt.CardLayout());

        passwordLabel.setText("Password:");

        titel.setText("Please Enter Username And Password");

        usernameLabel.setText("User Name:");

        permissionSubmitButton.setText("Submit");
        permissionSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout permissionPanelLayout = new javax.swing.GroupLayout(permissionPanel);
        permissionPanel.setLayout(permissionPanelLayout);
        permissionPanelLayout.setHorizontalGroup(
            permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, permissionPanelLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permissionPanelLayout.createSequentialGroup()
                        .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(permissionPasswordField)))
                    .addGroup(permissionPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(permissionSubmitButton))
                    .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );
        permissionPanelLayout.setVerticalGroup(
            permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permissionPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(permissionSubmitButton)
                .addGap(248, 248, 248))
        );

        permissionPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordLabel, permissionPasswordField});

        permissionMainPanel.add(permissionPanel, "card3");

        createForumMainPanel.setLayout(new java.awt.CardLayout());

        forumSubmitButton.setText("Submit");
        forumSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumSubmitButtonActionPerformed(evt);
            }
        });

        forumCancelButton.setText("Cancel");
        forumCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumCancelButtonActionPerformed(evt);
            }
        });

        openSubForumLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openSubForumLabel1.setText("Open new forum");
        openSubForumLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        forumPolicyLabel.setText("Policy:");

        forumNameLabel.setText("Forum Name:");

        forumSecurityLabel.setText("Security:");

        javax.swing.GroupLayout createForumPanelLayout = new javax.swing.GroupLayout(createForumPanel);
        createForumPanel.setLayout(createForumPanelLayout);
        createForumPanelLayout.setHorizontalGroup(
            createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createForumPanelLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createForumPanelLayout.createSequentialGroup()
                        .addComponent(openSubForumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createForumPanelLayout.createSequentialGroup()
                        .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forumPolicyLabel)
                            .addComponent(forumNameLabel)
                            .addComponent(forumSecurityLabel))
                        .addGap(30, 30, 30)
                        .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(forumSecurityText)
                            .addComponent(forumNameText)
                            .addComponent(forumPolicyText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
            .addGroup(createForumPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(forumSubmitButton)
                .addGap(59, 59, 59)
                .addComponent(forumCancelButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        createForumPanelLayout.setVerticalGroup(
            createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createForumPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(openSubForumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createForumPanelLayout.createSequentialGroup()
                        .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createForumPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(forumPolicyText))
                            .addComponent(forumNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(forumSecurityText))
                    .addGroup(createForumPanelLayout.createSequentialGroup()
                        .addComponent(forumNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(forumPolicyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(forumSecurityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(57, 57, 57)
                .addGroup(createForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forumSubmitButton)
                    .addComponent(forumCancelButton))
                .addGap(137, 137, 137))
        );

        createForumMainPanel.add(createForumPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permissionMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(registerMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(createSubMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(createForumMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permissionMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(registerMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(createSubMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(createForumMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void forumLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumLoginButtonActionPerformed
        permissionMainPanel.setVisible(true);
        mainPanel.setVisible(false);
        CardLayout cl = (CardLayout)(permissionMainPanel.getLayout());
        cl.first(permissionMainPanel);
        superAdminRegister = 1;
    }//GEN-LAST:event_forumLoginButtonActionPerformed
    
    private void permissionSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionSubmitButtonActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        permissionMainPanel.setVisible(false);
        mainPanel.setVisible(true);
        this.confirmed=true;
        userName = usernameTextField.getText();
        usernameTextField.setText("");
        
        if(isConfirmed()){
            this.confirmed=false;
            if (chosenForum == null){
                if(handler.validateSuperAdmin(userName, permissionPasswordField.getText()).contains("SUCCESS")){
//                System.out.println("$$$$$$$$$$$$");
                    buttonAppearance("superAdmin");
                    permissionPasswordField.setText("");
                    if (superAdminRegister == FORUMFRAME){
                        cl.first(mainPanel);
                        superAdminRegister = 0;
                    }
                    else if (superAdminRegister == SUBFORUMFRAME){
                        cl.first(mainPanel);
                        cl.next(mainPanel);
                        superAdminRegister = 0;
                    }
                    else {
                        cl.first(mainPanel);
                        cl.next(mainPanel);
                        cl.next(mainPanel);
                        superAdminRegister = 0;
                    }
                }
                else {
                    cl.first(mainPanel);
                    cl.next(mainPanel);
                }
            }
            else{
                serverResponse = handler.login(chosenForum, userName, permissionPasswordField.getText());
                permissionPasswordField.setText("");
//                if (serverResponse.contains("MEMBER")){
                if (serverResponse.contains("ADMIN"))
                    buttonAppearance("admin");
                else if(serverResponse.contains("MODERATOR"))
                    buttonAppearance("moderator");
                else
                    buttonAppearance("member");
            }
//                else
//                    JOptionPane.showMessageDialog(null, "Go home.. you are drunk!", "Bad Arguments",
//                                                            JOptionPane.PLAIN_MESSAGE);
//            }
        }
    }//GEN-LAST:event_permissionSubmitButtonActionPerformed
    
    private void subBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBackButtonActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
    }//GEN-LAST:event_subBackButtonActionPerformed
    
    private void registerSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSubmitButtonActionPerformed
        registerMainPanel.setVisible(false);
        mainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
        cl.next(mainPanel);
        if (handler.registerToForum(chosenForum, registerUserNameText.getText(), registerPasswordText.getText(), registerEmailText.getText(), registerRemainderQuesText.getText(), registerRemainderAnsText.getText()).contains("SUCCESS"))
            buttonAppearance("member");
        else buttonAppearance("guest");
        registerUserNameText.setText("");
        registerPasswordText.setText("");
        registerEmailText.setText("");
        registerRemainderQuesText.setText("");
        registerRemainderAnsText.setText("");
    }//GEN-LAST:event_registerSubmitButtonActionPerformed
    
    private void subRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRegistrationButtonActionPerformed
        registerMainPanel.setVisible(true);
        mainPanel.setVisible(false);
        CardLayout cl = (CardLayout)(registerMainPanel.getLayout());
        cl.first(registerMainPanel);
    }//GEN-LAST:event_subRegistrationButtonActionPerformed
    
    private void registerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCancelButtonActionPerformed
        registerMainPanel.setVisible(false);
        mainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
        cl.next(mainPanel);
    }//GEN-LAST:event_registerCancelButtonActionPerformed
    
    private void subLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLoginButtonActionPerformed
        mainPanel.setVisible(false);
        permissionMainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(permissionMainPanel.getLayout());
        cl.first(permissionMainPanel);
        superAdminRegister = 2;
    }//GEN-LAST:event_subLoginButtonActionPerformed
    
    private void subLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLogoutButtonActionPerformed
        handler.logout(chosenForum, userName);
        userName = "guest";
        buttonAppearance(userName);
    }//GEN-LAST:event_subLogoutButtonActionPerformed
    
    private void subAddAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAddAdminButtonActionPerformed
        String addedAdmin = JOptionPane.showInputDialog(null, "Enter administrator name to be added: ", "Add administrator",
                JOptionPane.PLAIN_MESSAGE);
        if (handler.addAdminToForum(chosenForum, addedAdmin)){
            Object[] os = new Object[1];
            os[0] = (Object)addedAdmin;
            adminsModel.addRow(os);
        }
        
    }//GEN-LAST:event_subAddAdminButtonActionPerformed
    
    private void subRemoveAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRemoveAdminButtonActionPerformed
        String removedAdmin = JOptionPane.showInputDialog(null, "Enter administrator name to be removed: ", "Remove administrator",
                JOptionPane.PLAIN_MESSAGE);
        if (handler.removeAdminFromForum(chosenForum, removedAdmin)){
            int index = getIndexOf(removedAdmin, adminsModel);
            adminsModel.removeRow(index);
        }
    }//GEN-LAST:event_subRemoveAdminButtonActionPerformed
    
    private void subCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCreateButtonActionPerformed
        mainPanel.setVisible(false);
        createSubMainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(createSubMainPanel.getLayout());
        cl.first(createSubMainPanel);
    }//GEN-LAST:event_subCreateButtonActionPerformed
    
    private void openSubSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSubSubmitButtonActionPerformed
        mainPanel.setVisible(true);
        createSubMainPanel.setVisible(false);
        String ans = handler.createSubForum(chosenForum, openSubNameText.getText(), openSubSubjectText.getText(), openSubModeratortext.getText(), userName);
        if(ans.contains("SUCCESS")){
            Object[] os = new Object[1];
            os[0] = (Object)openSubNameText.getText();
            allSubForumsModel.addRow(os);
        }
        openSubNameText.setText("");
        openSubSubjectText.setText("");
        openSubModeratortext.setText("");
        
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
        cl.next(mainPanel);
    }//GEN-LAST:event_openSubSubmitButtonActionPerformed
    
    private void openSubCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSubCancelButtonActionPerformed
        mainPanel.setVisible(true);
        createSubMainPanel.setVisible(false);
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
        cl.next(mainPanel);
    }//GEN-LAST:event_openSubCancelButtonActionPerformed
    
    private void subDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDeleteButtonActionPerformed
        String removedSubForum = JOptionPane.showInputDialog(null, "Enter sub forum name to be removed: ", "Remove sub forum",
                JOptionPane.PLAIN_MESSAGE);
        if (handler.deleteSubForum(chosenForum, removedSubForum).contains("SUCCESS")){
            int index = getIndexOf(removedSubForum, allSubForumsModel);
            allSubForumsModel.removeRow(index);
        }
    }//GEN-LAST:event_subDeleteButtonActionPerformed
    
    private void topicsRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsRegistrationButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_topicsRegistrationButtonActionPerformed
    
    private void topicsLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsLoginButtonActionPerformed
        mainPanel.setVisible(false);
        permissionMainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(permissionMainPanel.getLayout());
        cl.first(permissionMainPanel);
        superAdminRegister = 3;        
    }//GEN-LAST:event_topicsLoginButtonActionPerformed
    
    private void topicsLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsLogoutButtonActionPerformed
        userName = "guest";
        buttonAppearance(userName);
        handler.logout(chosenForum, userName);
    }//GEN-LAST:event_topicsLogoutButtonActionPerformed
    
    private void topicsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsBackButtonActionPerformed
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.previous(mainPanel);
    }//GEN-LAST:event_topicsBackButtonActionPerformed
    
    private void topicsDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsDeleteButtonActionPerformed
    
    private void topicsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsAddButtonActionPerformed
    
    private void topicsAddModeratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsAddModeratorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsAddModeratorButtonActionPerformed
    
    private void topicsRemoveModeratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsRemoveModeratorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsRemoveModeratorButtonActionPerformed
    
    private void forumCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumCreateButtonActionPerformed
        mainPanel.setVisible(false);
        createForumMainPanel.setVisible(true);
        CardLayout cl = (CardLayout)(createForumMainPanel.getLayout());
        cl.first(createForumMainPanel);
    }//GEN-LAST:event_forumCreateButtonActionPerformed
    
    private void forumSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumSubmitButtonActionPerformed
        mainPanel.setVisible(true);
        createForumMainPanel.setVisible(false);
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
        String ans = handler.createForum(forumNameText.getText(), forumPolicyText.getText(), forumSecurityText.getText());
        if(ans.startsWith("SUCCESS")){
            Object[][] data = convertToArray(handler.DisplayForums());
            String[] columnNames1 = {"Forum Name"};
            allForumsModel = new DefaultTableModel(data, columnNames1);
            forumsTable.setModel(allForumsModel);            
        }
        forumNameText.setText("");
        forumPolicyText.setText("");
        forumSecurityText.setText("");
    }//GEN-LAST:event_forumSubmitButtonActionPerformed
    
    private void forumCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumCancelButtonActionPerformed
        mainPanel.setVisible(true);
        createForumMainPanel.setVisible(false);
        CardLayout cl = (CardLayout)(mainPanel.getLayout());
        cl.first(mainPanel);
    }//GEN-LAST:event_forumCancelButtonActionPerformed
    
    private void forumDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumDeleteButtonActionPerformed
        String removedForum = JOptionPane.showInputDialog(null, "Enter forum name to be removed: ", "Remove forum",
                JOptionPane.PLAIN_MESSAGE);
        if (handler.deleteForum(removedForum)){
            int index = getIndexOf(removedForum, allForumsModel);
            allForumsModel.removeRow(index);
        }
    }//GEN-LAST:event_forumDeleteButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminsTable;
    private javax.swing.JPanel allForumsPanel;
    private javax.swing.JPanel allSubForumPanel;
    private javax.swing.JPanel allTopicsPanel;
    private javax.swing.JPanel createForumMainPanel;
    private javax.swing.JPanel createForumPanel;
    private javax.swing.JPanel createSubForumPanel;
    private javax.swing.JPanel createSubMainPanel;
    private javax.swing.JButton forumCancelButton;
    private javax.swing.JButton forumCreateButton;
    private javax.swing.JButton forumDeleteButton;
    private javax.swing.JButton forumLoginButton;
    private javax.swing.JLabel forumNameLabel;
    private javax.swing.JTextField forumNameText;
    private javax.swing.JLabel forumPolicyLabel;
    private javax.swing.JTextField forumPolicyText;
    private javax.swing.JLabel forumSecurityLabel;
    private javax.swing.JTextField forumSecurityText;
    private javax.swing.JButton forumSubmitButton;
    private javax.swing.JTable forumsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable moderatorsTable;
    private javax.swing.JButton openSubCancelButton;
    private javax.swing.JLabel openSubForumLabel;
    private javax.swing.JLabel openSubForumLabel1;
    private javax.swing.JLabel openSubModeratorLabel;
    private javax.swing.JTextField openSubModeratortext;
    private javax.swing.JLabel openSubNameLabel;
    private javax.swing.JTextField openSubNameText;
    private javax.swing.JLabel openSubSubjectLabel;
    private javax.swing.JTextField openSubSubjectText;
    private javax.swing.JButton openSubSubmitButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel permissionMainPanel;
    private javax.swing.JPanel permissionPanel;
    private javax.swing.JPasswordField permissionPasswordField;
    private javax.swing.JButton permissionSubmitButton;
    private javax.swing.JButton registerCancelButton;
    private javax.swing.JLabel registerEmailLabel;
    private javax.swing.JTextField registerEmailText;
    private javax.swing.JPanel registerMainPanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerPasswordText;
    private javax.swing.JLabel registerRemainderAnsLabel;
    private javax.swing.JTextField registerRemainderAnsText;
    private javax.swing.JLabel registerRemainderQuesLabel;
    private javax.swing.JTextField registerRemainderQuesText;
    private javax.swing.JButton registerSubmitButton;
    private javax.swing.JLabel registerToForumLabel;
    private javax.swing.JLabel registerUserNameLabel;
    private javax.swing.JTextField registerUserNameText;
    private javax.swing.JLabel saLabel;
    private javax.swing.JButton subAddAdminButton;
    private javax.swing.JButton subBackButton;
    private javax.swing.JButton subCreateButton;
    private javax.swing.JButton subDeleteButton;
    private javax.swing.JTable subForumTable;
    private javax.swing.JButton subLoginButton;
    private javax.swing.JButton subLogoutButton;
    private javax.swing.JButton subRegistrationButton;
    private javax.swing.JButton subRemoveAdminButton;
    private javax.swing.JLabel subWelcomeToLabel;
    private javax.swing.JLabel titel;
    private javax.swing.JButton topicsAddButton;
    private javax.swing.JButton topicsAddModeratorButton;
    private javax.swing.JButton topicsBackButton;
    private javax.swing.JButton topicsDeleteButton;
    private javax.swing.JButton topicsLoginButton;
    private javax.swing.JButton topicsLogoutButton;
    private javax.swing.JButton topicsRegistrationButton;
    private javax.swing.JButton topicsRemoveModeratorButton;
    private javax.swing.JTable topicsTable;
    private javax.swing.JLabel topicsWelcomeToLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    
    
    private Object[][] convertToArray(Vector<String> vec){
        Object[][] ans = new Object[vec.size()][1];
        for (int i = 0; i < vec.size(); i++)
            ans[i][0] = vec.elementAt(i);
        
        return ans;
        
    }
    
    private int getIndexOf(String forumToDelete, DefaultTableModel model) {
        for(int i=0; i<model.getRowCount(); i++)
            if(model.getValueAt(i, 0).equals(forumToDelete))
                return i;
        return -1;
    }
    
    public boolean isConfirmed() {
        return confirmed;
    }
    
    private void initTableListener(){
        //init all forum table:
        Object[][] data = convertToArray(handler.DisplayForums());
        String[] columnNames1 = {"Forum Name"};
        allForumsModel = new DefaultTableModel(data, columnNames1);
        forumsTable.setModel(allForumsModel);
        forumsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                
                chosenForum = forumsTable.getValueAt(forumsTable.getSelectedRow(), 0).toString();
                subWelcomeToLabel.setText("Welcome to " + chosenForum);
                CardLayout cl = (CardLayout)(mainPanel.getLayout());
                cl.first(mainPanel);
                cl.next(mainPanel);
            }
        });
        //init all sub forum table:
        data = convertToArray(handler.getSubForums(chosenForum));
        String[] columnNames2 = {"Sub Forum Name"};
        allSubForumsModel = new DefaultTableModel(data, columnNames2);
        subForumTable.setModel(allSubForumsModel);
        subForumTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                
                chosenSubForum = subForumTable.getValueAt(subForumTable.getSelectedRow(), 0).toString();
                topicsWelcomeToLabel.setText("Welcome to " + chosenSubForum);
                CardLayout cl = (CardLayout)(mainPanel.getLayout());
                cl.first(mainPanel);
                cl.next(mainPanel);
                cl.next(mainPanel);
            }
        });
        
        //init all admins table;
        data = convertToArray(handler.getAllAdminsInForum(chosenForum));
        String[] columnNames3 = {"Administrators"};
        adminsModel = new DefaultTableModel(data, columnNames3);
        adminsTable.setModel(adminsModel);
        
        //init all moderator table;
        data = convertToArray(handler.getAllModerators(chosenForum,chosenSubForum));
        String[] columnNames4 = {"Moderators"};
        moderatorsModel = new DefaultTableModel(data, columnNames4);
        moderatorsTable.setModel(moderatorsModel);
        
        //init all topics table:
        data = convertToArray(handler.getThreads(chosenForum,chosenSubForum));
        String[] columnNames5 = {"Topics Name"};
        allTopicsModel = new DefaultTableModel(data, columnNames5);
        topicsTable.setModel(allTopicsModel);
        topicsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            private String chosenTopic;
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                
                chosenTopic = forumsTable.getValueAt(forumsTable.getSelectedRow(), 0).toString();
                CardLayout cl = (CardLayout)(mainPanel.getLayout());
                cl.last(mainPanel);
            }
        });
        
        
        
        
    }
    
    private void buttonAppearance(String status){
        switch (status){
            case "superAdmin":
                //all forums page
                forumCreateButton.setVisible(true);
                forumDeleteButton.setVisible(true);
                saLabel.setVisible(false);
                forumLoginButton.setVisible(false);
                // sub forums page
                subAddAdminButton.setVisible(true);
                subBackButton.setVisible(true);
                subCreateButton.setVisible(true);
                subDeleteButton.setVisible(true);
                subLoginButton.setVisible(false);
                subLogoutButton.setVisible(true);
                subRegistrationButton.setVisible(false);
                subRemoveAdminButton.setVisible(true);
                //topics page:
                topicsAddButton.setVisible(true);
                topicsAddModeratorButton.setVisible(true);
                topicsBackButton.setVisible(true);
                topicsDeleteButton.setVisible(true);
                topicsLoginButton.setVisible(false);
                topicsLogoutButton.setVisible(true);
                topicsRegistrationButton.setVisible(false);
                topicsRemoveModeratorButton.setVisible(true);
                break;
            case "admin":
                //all forums page
                forumCreateButton.setVisible(false);
                forumDeleteButton.setVisible(false);
                saLabel.setVisible(true);
                forumLoginButton.setVisible(true);
                // sub forums page
                subAddAdminButton.setVisible(false);
                subBackButton.setVisible(true);
                subCreateButton.setVisible(true);
                subDeleteButton.setVisible(true);
                subLoginButton.setVisible(false);
                subLogoutButton.setVisible(true);
                subRegistrationButton.setVisible(false);
                subRemoveAdminButton.setVisible(false);
                //topics page:
                topicsAddButton.setVisible(true);
                topicsAddModeratorButton.setVisible(true);
                topicsBackButton.setVisible(true);
                topicsDeleteButton.setVisible(true);
                topicsLoginButton.setVisible(false);
                topicsLogoutButton.setVisible(true);
                topicsRegistrationButton.setVisible(false);
                topicsRemoveModeratorButton.setVisible(true);
                break;
            case "moderator":
                //all forums page
                forumCreateButton.setVisible(false);
                forumDeleteButton.setVisible(false);
                saLabel.setVisible(true);
                forumLoginButton.setVisible(true);
                // sub forums page
                subAddAdminButton.setVisible(false);
                subBackButton.setVisible(true);
                subCreateButton.setVisible(false);
                subDeleteButton.setVisible(false);
                subLoginButton.setVisible(false);
                subLogoutButton.setVisible(true);
                subRegistrationButton.setVisible(false);
                subRemoveAdminButton.setVisible(false);
                //topics page:
                topicsAddButton.setVisible(true);
                topicsAddModeratorButton.setVisible(false);
                topicsBackButton.setVisible(true);
                topicsDeleteButton.setVisible(true);
                topicsLoginButton.setVisible(false);
                topicsLogoutButton.setVisible(true);
                topicsRegistrationButton.setVisible(false);
                topicsRemoveModeratorButton.setVisible(false);
                break;
            case "member":
                //all forums page
                forumCreateButton.setVisible(false);
                forumDeleteButton.setVisible(false);
                saLabel.setVisible(true);
                forumLoginButton.setVisible(true);
                // sub forums page
                subAddAdminButton.setVisible(false);
                subBackButton.setVisible(true);
                subCreateButton.setVisible(false);
                subDeleteButton.setVisible(false);
                subLoginButton.setVisible(false);
                subLogoutButton.setVisible(true);
                subRegistrationButton.setVisible(false);
                subRemoveAdminButton.setVisible(false);
                //topics page:
                topicsAddButton.setVisible(true);
                topicsAddModeratorButton.setVisible(false);
                topicsBackButton.setVisible(true);
                topicsDeleteButton.setVisible(false);
                topicsLoginButton.setVisible(false);
                topicsLogoutButton.setVisible(true);
                topicsRegistrationButton.setVisible(false);
                topicsRemoveModeratorButton.setVisible(false);
                break;
            case "guest":
                //all forums page
                forumCreateButton.setVisible(false);
                forumDeleteButton.setVisible(false);
                saLabel.setVisible(true);
                forumLoginButton.setVisible(true);
                // sub forums page
                subAddAdminButton.setVisible(false);
                subBackButton.setVisible(true);
                subCreateButton.setVisible(false);
                subDeleteButton.setVisible(false);
                subLoginButton.setVisible(true);
                subLogoutButton.setVisible(false);
                subRegistrationButton.setVisible(true);
                subRemoveAdminButton.setVisible(false);
                //topics page:
                topicsAddButton.setVisible(false);
                topicsAddModeratorButton.setVisible(false);
                topicsBackButton.setVisible(true);
                topicsDeleteButton.setVisible(false);
                topicsLoginButton.setVisible(true);
                topicsLogoutButton.setVisible(false);
                topicsRegistrationButton.setVisible(true);
                topicsRemoveModeratorButton.setVisible(false);
                break;
        }
    }
}
